import { init } from '@airstack/airstack-react';
import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';

init(process.env.NEXT_PUBLIC_AIRSTACK_API_KEY ?? '');

export const metadata: Metadata = {
  title: 'UniFi',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#f1f1f1] font-cg_reg">
        {children}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
